__title__ = 'gitchm'
__url__ = 'https://github.com/ralphqq/gitchm'
__license__ = 'MIT License'
__package__ = 'gitchm'
__version__ = '0.1.0'
__short_description__ = 'CLI tool that copies commit history without reproducing the working tree'
__author__ = 'Ralph Quirequire'
__author_email__ = 'ralph.quirequire2012@gmail.com'
